
CREATE TABLE documents (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    folder_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fileuri VARCHAR(255) NOT NULL,
    revision INT(2),
    created DATETIME,
    modified DATETIME
);

CREATE TABLE folders (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    path VARCHAR(255) NOT NULL,
    created DATETIME,
    modified DATETIME
);
